-- CRIAÇÃO DA TABELA
CREATE TABLE ALUNO(
PK_ALUNO INT NOT NULL,
NOME_ALUNO VARCHAR(40),
RG_ALUNO CHAR(09),
CPF_ALUNO CHAR(11))

-- INSERÇÃO DA TABELA
INSERT INTO ALUNO(
	PK_ALUNO, 
	NOME_ALUNO
) VALUES (
	1, 
	'JUÃO'
);

-- SELECIONAR ITENS DA TABELA
SELECT * FROM ALUNO WHERE PK_ALUNO = 1;
